name: wild-workouts
services:
  api-build:
    volumes:
      - ./api/openapi:/spec
    image: redocly/cli
    command:
      [
        "join",
        "/spec/user.yaml",
        "/spec/demo.yaml",
        "-o",
        "/spec/merged/swagger.yaml"
      ]

  api-preview:
    depends_on: [ api-build ]
    volumes:
      - ./api/openapi:/spec
    image: redocly/cli
    ports:
      - "127.0.0.1:8080:8080"

    command: [ "preview-docs", "/spec/merged/swagger.yaml" ]

  demo-http:
    build:
      context: docker/service/local
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal/demo
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache

  portgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres/data/
    env_file:
      - .env
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
volumes:
  database:
