name: wild-workouts
services:
  api-doc:
    volumes:
      - ./api/openapi/merged/swagger.yaml:/usr/share/nginx/html/swagger.yaml
    image: redocly/redoc
    ports:
      - 8080:80
    environment:
      - SPEC_URL=swagger.yaml
  service_base:
    &service_base
    build:
      context: docker/service/local
    networks:
      default:
        aliases:
          - api.local

  demo-http:
    # hack for docker-compose v3 dropping `extends` support
    <<: *service_base
    build:
      context: docker/service/local
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal/demo
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
  user-http:
    # hack for docker-compose v3 dropping `extends` support
    <<: *service_base
    build:
      context: docker/local
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal/user
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache

  # demo-grpc:
  #   # hack for docker-compose v3 dropping `extends` support
  #   <<: *service_base
  #   build:
  #     context: docker/local
  #   volumes:
  #     - ./internal:/internal
  #     - ./.go/pkg:/go/pkg
  #     - ./.go-cache:/go-cache
  #   working_dir: /internal/demo
  #   ports:
  #     - "127.0.0.1:3001:$PORT"
  #   env_file:
  #     - .env
  #   environment:
  #     SERVER_TO_RUN: http
  #     GOCACHE: /go-cache

  portgres:
    # hack for docker-compose v3 dropping `extends` support
    <<: *service_base
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres/data/
    env_file:
      - .env

volumes:
  database:
