name: wild-workouts
services:
  demo-http:
    build:
      context: docker/local
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal/demo
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache

  portgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres/data/
    env_file:
      - .env
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
volumes:
  database:
