name: wild-workouts

services:
  api-doc:
    volumes:
      - ./api/openapi/swagger.yaml:/usr/share/nginx/html/swagger.yaml
    image: redocly/redoc
    ports:
      - 80:80
    environment:
      - SPEC_URL=swagger.yaml
