/**
 * API Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Test model module.
 * @module model/Test
 * @version 1.0
 */
class Test {
    /**
     * Constructs a new <code>Test</code>.
     * @alias module:model/Test
     * @param displayName {String} 
     */
    constructor(displayName) { 
        
        Test.initialize(this, displayName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, displayName) { 
        obj['displayName'] = displayName;
    }

    /**
     * Constructs a <code>Test</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Test} obj Optional instance to populate.
     * @return {module:model/Test} The populated <code>Test</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Test();

            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} displayName
 */
Test.prototype['displayName'] = undefined;






export default Test;

