// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
)

type NotifNotification struct {
	ID         uuid.UUID             `json:"id"`
	ReceiverID uuid.NullUUID         `json:"receiver_id"`
	Data       pqtype.NullRawMessage `json:"data"`
	IsSeen     sql.NullBool          `json:"is_seen"`
	Event      sql.NullString        `json:"event"`
	SenderID   uuid.NullUUID         `json:"sender_id"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
	DeletedAt  sql.NullTime          `json:"deleted_at"`
}

type NotifSetting struct {
	UserID uuid.UUID `json:"user_id"`
}
