// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetNotification(ctx context.Context, id uuid.UUID) (NotifNotification, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) error
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]NotifNotification, error)
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (NotifNotification, error)
}

var _ Querier = (*Queries)(nil)
