openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
  license: 
    name: DK
    url: this is license link
  
servers:
  - url: https://api.server.test/v1

security:
  - bearerAuth: []
paths:
  /demos:
    get:
      operationId: ListAllDemos
      summary: Get all of the demo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Demo'
        '404':
            description: Not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Demo:
      type: object
      required:
        - name
      properties:
        name:
          type: string