openapi: 3.0.0
servers:
  - url: //api.dev.tribe.tymetribe.com
    description: Default Server
info:
  version: 1.0.0
  title: Tribe API Documentation
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

security:
  - bearerAuth: []
paths:
  /demos:
    parameters:
      - name: Accept-Language
        in: header
        description: "The language you prefer for messages. Supported values are en-AU, en-CA, en-GB, en-US"
        example: en-US
        required: true
        schema:
          type: string
          default: en-AU
    get:
      operationId: ListCurrentUserDemos
      summary: Get all of user's the demo
      description: Get all of user's the demo
      parameters:
        - name: error
          in: query
          description: determine whether have error or not
          required: true
          style: form
          schema:
            type: boolean
          example: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Demo'
        '404':
            description: Not found
      tags: 
        - demo
    put:
      operationId: CreateCurrentUserDemo
      summary: Create current user demo
      description: Create current user demo
      requestBody: 
        $ref: '#/components/requestBodies/DemoRequest'
        
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Demo'
        '404':
            description: Not found
      tags: 
        - demo

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Demo:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: document 1
  requestBodies: 
    DemoRequest:
      content:
        application/json:
          schema:
            allOf:
              - description: My Demo
                title: Pettie
              - $ref: '#/components/schemas/Demo'
      description: Demo object that needs to be added to the store
      required: true
tags:
  - name: demo
    description: Everything about your Demo

x-tagGroups:
  - name: Demo Service
    tags:
      - demo
