openapi: 3.0.0
info:
  title: API Title
  version: '1.0'
  license: 
    name: DK
    url: this is license link
  
servers:
  - url: https://api.server.test/v1

security:
  - bearerAuth: []
paths:
  /user:
    get:
      operationId: GetUserInformation
      summary: Get user information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      tags: 
        -  user
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - displayName
        - balance
        - role
      properties:
        displayName:
          type: string
        balance:
          type: integer
        role:
          type: string

tags:
  - name: customer
    description: Everything about your Customer
  - name: user
    description: Everything about your User

x-tagGroups:
  - name:  User Management
    tags:
      - customer
      - user