// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: v1/events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocialMessageCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg         string                       `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Sender      *SocialMessageCreated_Sender `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	ReceiverIds []string                     `protobuf:"bytes,3,rep,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	CreatedAt   *timestamppb.Timestamp       `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *SocialMessageCreated) Reset() {
	*x = SocialMessageCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialMessageCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMessageCreated) ProtoMessage() {}

func (x *SocialMessageCreated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMessageCreated.ProtoReflect.Descriptor instead.
func (*SocialMessageCreated) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *SocialMessageCreated) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SocialMessageCreated) GetSender() *SocialMessageCreated_Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SocialMessageCreated) GetReceiverIds() []string {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *SocialMessageCreated) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SocialMessageCreated_Sender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ImageUrl  string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *SocialMessageCreated_Sender) Reset() {
	*x = SocialMessageCreated_Sender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialMessageCreated_Sender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMessageCreated_Sender) ProtoMessage() {}

func (x *SocialMessageCreated_Sender) ProtoReflect() protoreflect.Message {
	mi := &file_v1_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMessageCreated_Sender.ProtoReflect.Descriptor instead.
func (*SocialMessageCreated_Sender) Descriptor() ([]byte, []int) {
	return file_v1_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SocialMessageCreated_Sender) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SocialMessageCreated_Sender) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SocialMessageCreated_Sender) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SocialMessageCreated_Sender) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_v1_events_proto protoreflect.FileDescriptor

var file_v1_events_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x02,
	0x0a, 0x14, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x3e, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x1a, 0x71, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x69, 0x62, 0x65, 0x66, 0x69, 0x6e,
	0x74, 0x65, 0x63, 0x68, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_events_proto_rawDescOnce sync.Once
	file_v1_events_proto_rawDescData = file_v1_events_proto_rawDesc
)

func file_v1_events_proto_rawDescGZIP() []byte {
	file_v1_events_proto_rawDescOnce.Do(func() {
		file_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_events_proto_rawDescData)
	})
	return file_v1_events_proto_rawDescData
}

var file_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_events_proto_goTypes = []interface{}{
	(*SocialMessageCreated)(nil),        // 0: events.v1.SocialMessageCreated
	(*SocialMessageCreated_Sender)(nil), // 1: events.v1.SocialMessageCreated.Sender
	(*timestamppb.Timestamp)(nil),       // 2: google.protobuf.Timestamp
}
var file_v1_events_proto_depIdxs = []int32{
	1, // 0: events.v1.SocialMessageCreated.sender:type_name -> events.v1.SocialMessageCreated.Sender
	2, // 1: events.v1.SocialMessageCreated.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_events_proto_init() }
func file_v1_events_proto_init() {
	if File_v1_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialMessageCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialMessageCreated_Sender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_events_proto_goTypes,
		DependencyIndexes: file_v1_events_proto_depIdxs,
		MessageInfos:      file_v1_events_proto_msgTypes,
	}.Build()
	File_v1_events_proto = out.File
	file_v1_events_proto_rawDesc = nil
	file_v1_events_proto_goTypes = nil
	file_v1_events_proto_depIdxs = nil
}
