// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package ports

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Demo defines model for Demo.
type Demo struct {
	Name string `json:"name"`
}

// DemoRequest defines model for DemoRequest.
type DemoRequest struct {
	Name string `json:"name"`
}

// ListCurrentUserDemosParams defines parameters for ListCurrentUserDemos.
type ListCurrentUserDemosParams struct {
	// Error determine whether have error or not
	Error bool `form:"error" json:"error"`

	// AcceptLanguage The language you prefer for messages. Supported values are en-AU, en-CA, en-GB, en-US
	AcceptLanguage string `json:"Accept-Language"`
}

// CreateCurrentUserDemoJSONBody defines parameters for CreateCurrentUserDemo.
type CreateCurrentUserDemoJSONBody struct {
	Name string `json:"name"`
}

// CreateCurrentUserDemoParams defines parameters for CreateCurrentUserDemo.
type CreateCurrentUserDemoParams struct {
	// AcceptLanguage The language you prefer for messages. Supported values are en-AU, en-CA, en-GB, en-US
	AcceptLanguage string `json:"Accept-Language"`
}

// CreateCurrentUserDemoJSONRequestBody defines body for CreateCurrentUserDemo for application/json ContentType.
type CreateCurrentUserDemoJSONRequestBody CreateCurrentUserDemoJSONBody
