.PHONY: cognitostub
cognitostub:
	@tput setaf 2;echo "generate cognito mock stub"
	@mockgen -destination ./mock/mock_cognitoidentityprovideriface/cognitoidentityprovideriface.go github.com/aws/aws-sdk-go/service/cognitoidentityprovider/cognitoidentityprovideriface CognitoIdentityProviderAPI 