// Code generated by sqlc. DO NOT EDIT.
// source: demo.sql

package sqlc

import (
	"context"
)

const getDemo = `-- name: GetDemo :one
SELECT id, name FROM demo
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDemo(ctx context.Context, id int64) (Demo, error) {
	row := q.db.QueryRowContext(ctx, getDemo, id)
	var i Demo
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
