name: PR Notif Review

on:
  pull_request:
    paths:
      - internal/notif/*
      - internal/common/*
      - .github/workflows/notif.pr.yaml

jobs:
  reviewdog:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Linter
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          level: error
  test:
    runs-on: ubuntu-latest
    needs: reviewdog
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Test
        run: cd ./internal/notif && go test ./...
